services:
  backend:
    build: .
    container_name: DevTasks_Backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: DevTasks_Frontend
    ports:
      - "3030:3030"

  database:
    container_name: postgres_database
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB=devtask_db
      - POSTGRES_USER=ador
      - POSTGRES_PASSWORD=12345678

  adminer:
    container_name: postgres_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"